### ISSUE TITLE
Basic analytics / code review SLAs

### ISSUE THREAD

**Issue by spladug** [spladug/harold#49]
whilst we wait for pull panda

**Comment by gtaylor** [comment]
Highly interested in this from the perspective of an EM. As the org has scaled, we've seen some growing pains on the review front. We have org guidelines on responsiveness for PRs, but it's super difficult to check to see how we're doing without manually checking everyone's Salons.

Some things that I'd be excited about:

* Having some stats on per-reviewer responsiveness would make it much easier to coach review etiquette (not necessarily immediate review, but quickly chiming in if the reviewer is unable or unwilling to review rather than letting a PR sit).
* Being able to more easily recognize our most prolific reviewers.
* Having some metrics would also make it easier for to check with our most prolific reviewers to make sure they are opting into that high volume (rather than being defacto summoned on all the things).
* We see so many PRs in Infra that it is difficult to draw conclusions about what the total firehose of reviews is looking like. Are they generally big? Small? Do they require lots of back-and-forth? Are authors generally responsive, or are we missing one another for extended periods of time? Having some quantifiable metrics on the time it takes various parts of the review, how many comments are flying, the nature of the change (commits, additions/deletions) and etc might help surface some patterns that would influence our roadmap.
* I have a fuzzy notion of what percentage of our sprint is spent on review, but we'd be able to get closer to quantifying it with the help of some metrics.

Some metrics that would be valuable for my particular usage cases:

* A series for each PR summons (PR + each :eyeglasses:'d reviewer) that separately tracks time to first interaction. Interaction is defined as any kind of emoji response. In a future where we are really fancy, this would ideally include PR comments.
* Or maybe rather than just time to first interaction, time in each phase per reviewer? ex: tracking separately time spent in :see_no_evil: then :nail_care: before landing on :fish: ?
* If we can't get it from the above series, a metric for frequency of a :running: response. There have been a few cases where this has been leaned on too frequently while also taking us a while to notice and coach out!
* This might be a "later" metric, but having a comment count for the PR would help us suss out expensive or difficult reviews.
* Lower priority: # commits and/or additions/deletions per review. This might fluctuate from rebases. This might be combinable with the comment count and age metrics to make up some kind of "cost" factor that we could watch out for.
